site_name: Documentação Mamutes do Cerrado

nav:
  - Apresentação: index.md

  - Atas de reuniao:
      - Cliente:
          - Ata 1: "atas-reuniao/cliente/ata-reuniao-1.md"
          - Ata 2: "atas-reuniao/cliente/ata-reuniao-2.md"
          - Ata 3: "atas-reuniao/cliente/ata-reuniao-3.md"
          - Ata 4: "atas-reuniao/cliente/ata-reuniao-4.md"
          - Ata 5: "atas-reuniao/cliente/ata-reuniao-5.md"

      - Equipe:
          - Ata 1: "atas-reuniao/equipe/ata-reuniao-1-equipe.md"
          - Ata 2: "atas-reuniao/equipe/ata-reuniao-2-equipe.md"
          - Ata 3: "atas-reuniao/equipe/ata-reuniao-3-equipe.md"
          - Ata 4: "atas-reuniao/equipe/ata-reuniao-4-equipe.md"
          - Ata 5: "atas-reuniao/equipe/ata-reuniao-5-equipe.md"
          - Ata 6: "atas-reuniao/equipe/ata-reuniao-6-equipe.md"

  - Documentação de Visão: "documento-visao/documento-visao.md"
  - Documentação de Requisitos: "documento-requisitos/documento-requisitos.md"
  - Documentação de Arquitetura: "documento-arquitetura/documento-arquitetura.md"
  - Documentação do Plano de Testes: "documento-plano-testes/documento-plano-testes.md"

theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  language: pt

styles_css:
  - view/css/styles.css